### ISSUE TITLE
Reconciliation against AAT

### ISSUE THREAD

**Issue by RolfBly** [netwerk-digitaal-erfgoed/network-of-terms#782]
Note: this is a question where you're heading rather than an issue. Or perhaps a usability issue. 

As far as I can tell, reconciliation from OpenRefine against 

https://termennetwerk-api.netwerkdigitaalerfgoed.nl/reconcile/http://vocab.getty.edu/aat/sparql

retrieves just the Dutch literal of any term found. Is this considered a finalised feature? 

Reconciling via Getty's url retrieves a url to the term, to which one can apply OR's [expressions for recon](https://docs.openrefine.org/manual/expressions#reconciliation). After which one could use the AAT ID to retrieve further info, such as scope note.

**Comment by coret** [comment]
The AAT wasn't included in the Network of Terms Reconciliation API because the AAT has it's own Reconciliation API (see https://www.getty.edu/research/tools/vocabularies/obtain/openrefine.html). Issue some Dutch users had with this service is that although you can search for Dutch terms, only English matches are shown. After consulting with the Getty Vocabulary program, who acknowlegdes the lack of language switching and have put it on their todo-list, we decided to include the AAT in the Network of Terms Reconciliation API specifically to show Dutch matches.

You can get further information about a term via Open Refines expressions, but that after you have accepted a match (English of Dutch).

**Comment by RolfBly** [comment]
Thanks, this is the good news 

> Getty Vocabulary program [...] acknowlegdes the lack of language switching and have put it on their todo-list

For now, I guess it means reconciling twice for those who want more. Which is OK.
